/* theme-gtkcss.c generated by valac 0.48.6, the Vala compiler
 * generated from theme-gtkcss.vala, do not modify */

/*
 *  Notes - panel plugin for Xfce Desktop Environment
 *  Copyright (c) 2006-2013  Mike Massonnet <mmassonnet@xfce.org>
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA
 */

#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <glib.h>
#include <gdk/gdk.h>
#include <config.h>
#include <glib/gstdio.h>
#include <gtk/gtk.h>

#define XNP_TYPE_THEME_GTKCSS (xnp_theme_gtkcss_get_type ())
#define XNP_THEME_GTKCSS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), XNP_TYPE_THEME_GTKCSS, XnpThemeGtkcss))
#define XNP_THEME_GTKCSS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), XNP_TYPE_THEME_GTKCSS, XnpThemeGtkcssClass))
#define XNP_IS_THEME_GTKCSS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), XNP_TYPE_THEME_GTKCSS))
#define XNP_IS_THEME_GTKCSS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), XNP_TYPE_THEME_GTKCSS))
#define XNP_THEME_GTKCSS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), XNP_TYPE_THEME_GTKCSS, XnpThemeGtkcssClass))

typedef struct _XnpThemeGtkcss XnpThemeGtkcss;
typedef struct _XnpThemeGtkcssClass XnpThemeGtkcssClass;
typedef struct _XnpThemeGtkcssPrivate XnpThemeGtkcssPrivate;
enum  {
	XNP_THEME_GTKCSS_0_PROPERTY,
	XNP_THEME_GTKCSS_NUM_PROPERTIES
};
static GParamSpec* xnp_theme_gtkcss_properties[XNP_THEME_GTKCSS_NUM_PROPERTIES];
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _XnpThemeGtkcss {
	GObject parent_instance;
	XnpThemeGtkcssPrivate * priv;
};

struct _XnpThemeGtkcssClass {
	GObjectClass parent_class;
};

static gpointer xnp_theme_gtkcss_parent_class = NULL;

GType xnp_theme_gtkcss_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (XnpThemeGtkcss, g_object_unref)
gchar* xnp_theme_gtkcss_get_css_path (void);
void xnp_theme_gtkcss_update_css (GdkColor* color);
void xnp_theme_gtkcss_update_style_context (void);
XnpThemeGtkcss* xnp_theme_gtkcss_new (void);
XnpThemeGtkcss* xnp_theme_gtkcss_construct (GType object_type);
static GType xnp_theme_gtkcss_get_type_once (void);

gchar*
xnp_theme_gtkcss_get_css_path (void)
{
	const gchar* _tmp0_;
	gchar* _tmp1_;
	gchar* result = NULL;
	_tmp0_ = g_get_user_config_dir ();
	_tmp1_ = g_strdup_printf ("%s/xfce4/xfce4-notes.css", _tmp0_);
	result = _tmp1_;
	return result;
}

void
xnp_theme_gtkcss_update_css (GdkColor* color)
{
	gchar* css = NULL;
	GdkColor _tmp0_;
	GdkColor _tmp1_;
	GdkColor _tmp2_;
	gchar* _tmp3_;
	GError* _inner_error0_ = NULL;
	g_return_if_fail (color != NULL);
	_tmp0_ = *color;
	_tmp1_ = *color;
	_tmp2_ = *color;
	_tmp3_ = g_strdup_printf ("@define-color notes_bg_color #%x%x%x;\n" \
"@import url(\"%s%c%s%cgtk-main.css\");", (guint) (_tmp0_.red >> 8), (guint) (_tmp1_.green >> 8), (guint) (_tmp2_.blue >> 8), PKGDATADIR, (gint) G_DIR_SEPARATOR, "gtk-3.0", (gint) G_DIR_SEPARATOR);
	css = _tmp3_;
	{
		gchar* _tmp4_;
		gchar* _tmp5_;
		_tmp4_ = xnp_theme_gtkcss_get_css_path ();
		_tmp5_ = _tmp4_;
		g_file_set_contents (_tmp5_, css, (gssize) -1, &_inner_error0_);
		_g_free0 (_tmp5_);
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
			if (_inner_error0_->domain == G_FILE_ERROR) {
				goto __catch0_g_file_error;
			}
			_g_free0 (css);
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
			g_clear_error (&_inner_error0_);
			return;
		}
	}
	goto __finally0;
	__catch0_g_file_error:
	{
		GError* e = NULL;
		GError* _tmp6_;
		const gchar* _tmp7_;
		e = _inner_error0_;
		_inner_error0_ = NULL;
		_tmp6_ = e;
		_tmp7_ = _tmp6_->message;
		g_warning ("theme-gtkcss.vala:34: Unable to update CSS file: %s", _tmp7_);
		_g_error_free0 (e);
	}
	__finally0:
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		_g_free0 (css);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
		g_clear_error (&_inner_error0_);
		return;
	}
	_g_free0 (css);
}

void
xnp_theme_gtkcss_update_style_context (void)
{
	GError* _inner_error0_ = NULL;
	{
		GtkCssProvider* cssprovider = NULL;
		GtkCssProvider* _tmp0_;
		gchar* _tmp1_;
		gchar* _tmp2_;
		GdkScreen* _tmp3_;
		_tmp0_ = gtk_css_provider_new ();
		cssprovider = _tmp0_;
		_tmp1_ = xnp_theme_gtkcss_get_css_path ();
		_tmp2_ = _tmp1_;
		gtk_css_provider_load_from_path (cssprovider, _tmp2_, &_inner_error0_);
		_g_free0 (_tmp2_);
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
			_g_object_unref0 (cssprovider);
			goto __catch0_g_error;
		}
		_tmp3_ = gdk_screen_get_default ();
		gtk_style_context_add_provider_for_screen (_tmp3_, (GtkStyleProvider*) cssprovider, (guint) GTK_STYLE_PROVIDER_PRIORITY_USER);
		_g_object_unref0 (cssprovider);
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError* e = NULL;
		GError* _tmp4_;
		const gchar* _tmp5_;
		e = _inner_error0_;
		_inner_error0_ = NULL;
		_tmp4_ = e;
		_tmp5_ = _tmp4_->message;
		g_warning ("theme-gtkcss.vala:44: %s", _tmp5_);
		_g_error_free0 (e);
	}
	__finally0:
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
		g_clear_error (&_inner_error0_);
		return;
	}
}

XnpThemeGtkcss*
xnp_theme_gtkcss_construct (GType object_type)
{
	XnpThemeGtkcss * self = NULL;
	self = (XnpThemeGtkcss*) g_object_new (object_type, NULL);
	return self;
}

XnpThemeGtkcss*
xnp_theme_gtkcss_new (void)
{
	return xnp_theme_gtkcss_construct (XNP_TYPE_THEME_GTKCSS);
}

static void
xnp_theme_gtkcss_class_init (XnpThemeGtkcssClass * klass,
                             gpointer klass_data)
{
	xnp_theme_gtkcss_parent_class = g_type_class_peek_parent (klass);
}

static void
xnp_theme_gtkcss_instance_init (XnpThemeGtkcss * self,
                                gpointer klass)
{
}

static GType
xnp_theme_gtkcss_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (XnpThemeGtkcssClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) xnp_theme_gtkcss_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (XnpThemeGtkcss), 0, (GInstanceInitFunc) xnp_theme_gtkcss_instance_init, NULL };
	GType xnp_theme_gtkcss_type_id;
	xnp_theme_gtkcss_type_id = g_type_register_static (G_TYPE_OBJECT, "XnpThemeGtkcss", &g_define_type_info, 0);
	return xnp_theme_gtkcss_type_id;
}

GType
xnp_theme_gtkcss_get_type (void)
{
	static volatile gsize xnp_theme_gtkcss_type_id__volatile = 0;
	if (g_once_init_enter (&xnp_theme_gtkcss_type_id__volatile)) {
		GType xnp_theme_gtkcss_type_id;
		xnp_theme_gtkcss_type_id = xnp_theme_gtkcss_get_type_once ();
		g_once_init_leave (&xnp_theme_gtkcss_type_id__volatile, xnp_theme_gtkcss_type_id);
	}
	return xnp_theme_gtkcss_type_id__volatile;
}

