/* theme.c generated by valac 0.48.6, the Vala compiler
 * generated from theme.vala, do not modify */

/*
 *  Notes - panel plugin for Xfce Desktop Environment
 *  Copyright (c) 2006-2013  Mike Massonnet <mmassonnet@xfce.org>
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA
 */

#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <glib.h>
#include <gdk/gdk.h>

#define XNP_TYPE_THEME (xnp_theme_get_type ())
#define XNP_THEME(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), XNP_TYPE_THEME, XnpTheme))
#define XNP_THEME_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), XNP_TYPE_THEME, XnpThemeClass))
#define XNP_IS_THEME(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), XNP_TYPE_THEME))
#define XNP_IS_THEME_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), XNP_TYPE_THEME))
#define XNP_THEME_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), XNP_TYPE_THEME, XnpThemeClass))

typedef struct _XnpTheme XnpTheme;
typedef struct _XnpThemeClass XnpThemeClass;
typedef struct _XnpThemePrivate XnpThemePrivate;
enum  {
	XNP_THEME_0_PROPERTY,
	XNP_THEME_NUM_PROPERTIES
};
static GParamSpec* xnp_theme_properties[XNP_THEME_NUM_PROPERTIES];

struct _XnpTheme {
	GObject parent_instance;
	XnpThemePrivate * priv;
};

struct _XnpThemeClass {
	GObjectClass parent_class;
};

static gpointer xnp_theme_parent_class = NULL;

GType xnp_theme_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (XnpTheme, g_object_unref)
void xnp_theme_set_background_color (const gchar* color);
void xnp_theme_gtkcss_update_css (GdkColor* color);
void xnp_theme_gtkcss_update_style_context (void);
XnpTheme* xnp_theme_new (void);
XnpTheme* xnp_theme_construct (GType object_type);
static GType xnp_theme_get_type_once (void);

void
xnp_theme_set_background_color (const gchar* color)
{
	GdkColor gdkcolor = {0};
	GdkColor _tmp0_ = {0};
	gboolean _tmp1_;
	GdkColor _tmp2_;
	g_return_if_fail (color != NULL);
	_tmp1_ = gdk_color_parse (color, &_tmp0_);
	gdkcolor = _tmp0_;
	if (!_tmp1_) {
		g_warning ("theme.vala:27: Cannot parse background color %s", color);
		return;
	}
	_tmp2_ = gdkcolor;
	xnp_theme_gtkcss_update_css (&_tmp2_);
	xnp_theme_gtkcss_update_style_context ();
}

XnpTheme*
xnp_theme_construct (GType object_type)
{
	XnpTheme * self = NULL;
	self = (XnpTheme*) g_object_new (object_type, NULL);
	return self;
}

XnpTheme*
xnp_theme_new (void)
{
	return xnp_theme_construct (XNP_TYPE_THEME);
}

static void
xnp_theme_class_init (XnpThemeClass * klass,
                      gpointer klass_data)
{
	xnp_theme_parent_class = g_type_class_peek_parent (klass);
}

static void
xnp_theme_instance_init (XnpTheme * self,
                         gpointer klass)
{
}

static GType
xnp_theme_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (XnpThemeClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) xnp_theme_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (XnpTheme), 0, (GInstanceInitFunc) xnp_theme_instance_init, NULL };
	GType xnp_theme_type_id;
	xnp_theme_type_id = g_type_register_static (G_TYPE_OBJECT, "XnpTheme", &g_define_type_info, 0);
	return xnp_theme_type_id;
}

GType
xnp_theme_get_type (void)
{
	static volatile gsize xnp_theme_type_id__volatile = 0;
	if (g_once_init_enter (&xnp_theme_type_id__volatile)) {
		GType xnp_theme_type_id;
		xnp_theme_type_id = xnp_theme_get_type_once ();
		g_once_init_leave (&xnp_theme_type_id__volatile, xnp_theme_type_id);
	}
	return xnp_theme_type_id__volatile;
}

